[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
duckdb = { version = "1.1", features = ["bundled", "r2d2", "chrono"] }
r2d2 = "0.8"
utoipa = { version = "5", features = ["chrono"] }
thiserror = "2.0"
anyhow = "1.0"
tracing = "0.1"
clap = { version = "4.5", features = ["derive", "env"] }
