export interface ProcedurePreset {
  code: string;
  name: string;
  codeType: 'cpt' | 'hcpcs' | 'ms_drg';
  category: string;
}

export const COMMON_PROCEDURES: ProcedurePreset[] = [
  {
    code: '99213',
    name: 'Office/Outpatient Visit (15 min)',
    codeType: 'cpt',
    category: 'Evaluation & Management',
  },
  {
    code: '99214',
    name: 'Office/Outpatient Visit (25 min)',
    codeType: 'cpt',
    category: 'Evaluation & Management',
  },
  {
    code: '470',
    name: 'Major Joint Replacement (Knee/Hip)',
    codeType: 'ms_drg',
    category: 'Inpatient Surgery',
  },
  {
    code: '70551',
    name: 'MRI Brain Scan without Contrast',
    codeType: 'cpt',
    category: 'Imaging & Radiology',
  },
  {
    code: '45378',
    name: 'Diagnostic Colonoscopy',
    codeType: 'cpt',
    category: 'Diagnostic Endoscopy',
  },
  {
    code: '80053',
    name: 'Comprehensive Metabolic Panel',
    codeType: 'cpt',
    category: 'Laboratory Test',
  },
  {
    code: '71045',
    name: 'Chest X-Ray Single View',
    codeType: 'cpt',
    category: 'Imaging & Radiology',
  },
  {
    code: '93000',
    name: 'Electrocardiogram (ECG/EKG)',
    codeType: 'cpt',
    category: 'Cardiology',
  },
];

export const US_STATES = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'DC', name: 'District of Columbia' },
  { code: 'PR', name: 'Puerto Rico' },
];

export const MAJOR_PAYERS = [
  'Aetna',
  'Blue Cross Blue Shield',
  'Cigna',
  'UnitedHealthcare',
  'Humana',
  'Kaiser Permanente',
  'Medicare Advantage',
  'Medicaid MCO',
];
